[project]
name = "GradescopeAPI"
version = "1.0.0"
description = "Library for programmatically interacting with Gradescope."
authors = [
    { name = "Susmitha Kusuma", email = "sk10689@nyu.edu" },
    { name = "Berry Liu", email = "bl3056@nyu.edu" },
    { name = "Margaret Jagger", email = "mj3102@nyu.edu" },
    { name = "Calvin Tian", email = "calvin.tian@nyu.edu" },
    { name = "Kevin Zheng", email = "kz1252@nyu.edu" },
]
dependencies = [
    "pytest>=8.0.0",
    "beautifulsoup4>=4.12.3",
    "requests>=2.31.0",
    "python-dotenv>=1.0.1",
    "fastapi>=0.111.0",
]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "black>=24.1.1",
    "mypy>=1.8.0",
    "pre-commit>=3.7.0",
    "ruff>=0.4.3",
]

[tool.pdm.scripts]
start = "python -m sylveon"
test = "pytest tests"
lint = "mypy src tests"
format = "black src tests"
format-test = "black --check src tests"
export = "pdm export -f requirements -o requirements.txt --without-hashes"
